// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdMVxrpBlMq14p__LFgqD676V2nKU4Igc',
    appId: '1:390947613185:web:bb6d5da72f384551536e00',
    messagingSenderId: '390947613185',
    projectId: 'backendfirst-8df89',
    authDomain: 'backendfirst-8df89.firebaseapp.com',
    storageBucket: 'backendfirst-8df89.firebasestorage.app',
    measurementId: 'G-YVT3S0LXWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC09V7Aon8LwGhcCY7TMQi-ofCoAHRX8M0',
    appId: '1:390947613185:android:1a4aaf3805d24cda536e00',
    messagingSenderId: '390947613185',
    projectId: 'backendfirst-8df89',
    storageBucket: 'backendfirst-8df89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtli5RB3OILaVUiAPobCk1YfWsVzm35_8',
    appId: '1:390947613185:ios:8d1e35ed80a885b5536e00',
    messagingSenderId: '390947613185',
    projectId: 'backendfirst-8df89',
    storageBucket: 'backendfirst-8df89.firebasestorage.app',
    iosBundleId: 'com.example.firebaseOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtli5RB3OILaVUiAPobCk1YfWsVzm35_8',
    appId: '1:390947613185:ios:8d1e35ed80a885b5536e00',
    messagingSenderId: '390947613185',
    projectId: 'backendfirst-8df89',
    storageBucket: 'backendfirst-8df89.firebasestorage.app',
    iosBundleId: 'com.example.firebaseOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdMVxrpBlMq14p__LFgqD676V2nKU4Igc',
    appId: '1:390947613185:web:a25e23d96a8152fe536e00',
    messagingSenderId: '390947613185',
    projectId: 'backendfirst-8df89',
    authDomain: 'backendfirst-8df89.firebaseapp.com',
    storageBucket: 'backendfirst-8df89.firebasestorage.app',
    measurementId: 'G-01GKCWP0DR',
  );
}
